# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171013_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sulg',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
