# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sulg',
            new_name='slug',
        ),
    ]
